travis:
  secure:
    BINSTAR_TOKEN: BrvQ/srmi+Bry2/iinAQPwCtNXfFR+YpHMhBMqZIQKBij+wFPe++EIyveIwtS9oGU07z0+rRZAZrjZ+2MGsYvZrtpHNLOQ4DnPk/Xb4YSIwyjbEs+uzGFeuSICMIGIoLgjclBAbE03n/JnZ5NbVQRL6N2UCrfpiS0nuwoFo0cEgeVGATIGJn7LLOPGWFDKfYWDpn0HdEnT6keaJ5e2gjKzo5qTm7EYx1rWKdCOTonyYQIAihnVyBVJ3+k9RBH97GGkPun2c+BhzyVAT4S9VBJ1MLuhbK0Q1yPSFA4z4HR5u3ej3gzLY3mJ30gm2yW059xv/zIA6acvIgtiNorxSxfkXoNHGXFHyQvLElUeEE1/xuIl2R0rnatK1i9tnC00srbEZPYbkoMpTVupmbVlFSUFQ01tyTscGFNNv/gHSeXEHnP+L5gwIaSvJRtrI1Y6Z6+g7TcLaCvyJjGrsq/RiiVm740hh2/eJ21rMTwzReL8+LdvxET3X4JN8Zz+3XV2c9ClX6OCVFDW55TqfApZ+1CdQkXR3o+CxKYgb5U624YWZtOhbjlGE7o8iX9EX3E8QJZilRwsewRWDQDwwfp8nCWhe77JzSGQlttttm6mgVT4WrnmrWoKaXEGuY5LzjmcL/+z70eGUIuRTCwa3osy+P/AHKKnGokB19dfobTt1fGEM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
